import React, { createContext, useState, useContext } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Home Screen
    'app.title': 'Find A Match',
    'app.subtitle': 'Find your next match!',
    'app.pendingRequests': 'Pending Requests',
    'app.myRequests': 'My Requests',
    'app.myPendingRequests': 'My Pending Requests',
    'app.incomingRequests': 'Requests From Friends',
    'app.confirmedMatches': 'Confirmed Matches',
    'app.cancelledRequests': 'Cancelled Requests',
    'app.noRequests': 'No requests yet',
    'app.noRequestsSubtext': 'Tap the + button to create one!',
    'app.cancelled': 'Cancelled',
    'app.acceptedCount': '{count}/{total} accepted',
    'app.accepted': 'Accepted',
    'app.declined': 'Declined',
    'app.declinedBy': 'Declined by',
    'app.allDeclined': 'All declined',
    'app.actionRequired': 'Action required',
    'app.waitingForFriends': 'Waiting for friends',
    'app.incomingResponded': 'You already responded',
    'app.creator': 'Creator',
    'app.with': 'With',
    'app.friendsInvitedOne': '1 friend invited',
    'app.friendsInvitedCount': '{count} friends invited',
    'home.newFriendRequestOne': '1 new friend request',
    'home.newFriendRequestCount': '{count} new friend requests',
    
    // Request Screen
    'request.title': 'New Request',
    'request.date': 'Date',
    'request.timeSection': 'Time',
    'request.timeRangeMode': 'Time range',
    'request.exactTimeMode': 'Exact time',
    'request.timeRangeHint': 'Friend can choose when within this range',
    'request.exactTimeHint': 'Match is at this exact time',
    'request.startTime': 'Start',
    'request.endTime': 'End',
    'request.selectSport': 'Select Sport',
    'request.selectFriends': 'Select Friends',
    'request.selected': 'selected',
    'request.noFriends': 'No friends yet',
    'request.noFriendsSubtext': 'Add friends to your list to send tennis requests',
    'request.noFriendsForSport': 'No friends with this sport yet',
    'request.send': 'Send Request',
    'request.errorNoFriends': 'Please select at least one friend',
    'request.errorNoSport': 'Please select a sport',
    'request.errorTime': 'End time must be after start time',
    'request.players': 'Players',
    'request.inviteAll': 'Invite all',
    'request.inviteAllWithCount': 'Invite all ({count})',
    'request.inviteSome': 'Select friends',
    'request.inviteSomeWithCount': 'Select friends ({count})',
    'request.errorPlayers': 'Please enter a valid number of players',
    'request.errorPlayersTooMany': 'Not enough friends for this number of players',
    'request.locationOptional': 'Location (optional)',
    'request.locationPlaceholder': 'e.g. Tennis Club, Park XYZ',
    'request.comment': 'Comment (visible to all)',
    'request.commentPlaceholder': 'e.g. Bring your own balls, court 3 reserved...',
    'request.durationOptional': 'Duration (optional, minutes)',
    'request.durationRequired': 'Duration (minutes)',
    'request.durationPlaceholder': 'e.g. 120',
    'request.durationCalculated': 'Duration',
    'request.errorDuration': 'Please enter a valid duration',
    'request.errorDurationRequired': 'Please enter duration for time range',
    'request.update': 'Update Request',
    'request.success': 'Success',
    'request.sent': 'Request sent to {count} friend(s)!',
    
    // Request Details
    'details.title': 'Match',
    'details.titleWithSport': '{sport} Match',
    'details.headerTitle': 'Request Details',
    'details.confirmed': '✓ Confirmed',
    'details.date': 'Date:',
    'details.time': 'Time:',
    'details.timeRange': 'Time Range:',
    'details.sport': 'Sport:',
    'details.location': 'Location:',
    'details.comment': 'Comment:',
    'details.friendsInvited': 'Friends Invited:',
    'details.participants': 'Participants',
    'details.you': '(You)',
    'details.organizer': 'Organizer',
    'details.accepted': '✓ Accepted:',
    'details.acceptTime': 'Confirm Match',
    'details.startTime': 'Start',
    'details.endTime': 'End',
    'details.waiting': 'Waiting for response...',
    'details.proposed': 'Proposed:',
    'details.accept': 'Accept',
    'details.decline': 'Decline',
    'details.declineMatch': 'Decline match',
    'details.declineMatchConfirm': 'Are you sure you want to decline this match? This cannot be undone.',
    'details.declined': 'Declined',
    'details.withdrawn': 'Withdrawn',
    'details.durationOutOfRange': 'Selected time does not match the requested duration',
    'details.duration': 'Duration:',
    'details.suggestedTimes': 'Suggested times',
    'details.deleteRequest': 'Delete request',
    'details.deleteConfirm': 'Do you want to delete this request?',
    'details.editRequest': 'Edit request',
    'details.editRequestPrompt': 'Do you want to edit this request?',
    'details.acceptedBy': 'Accepted by',
    'details.declinedBy': 'Declined by',
    'details.hasDeclines': 'Cannot confirm while someone has declined',
    'details.confirmMatch': 'Confirm Match',
    'details.errorNoAcceptances': 'No friends have accepted a time yet',
    'details.matchConfirmed': 'Match confirmed!',
    'details.onlyCreatorConfirm': 'Only the creator can confirm the match.',
    'details.completed': 'Completed',
    'details.completeMatch': 'Mark as Played',
    'details.completeMatchConfirm': 'Mark this match as played?',
    'details.matchCompleted': 'Match marked as played!',
    'details.cancelRequest': 'Cancel Request',
    'details.cancelConfirm': 'Do you want to cancel this request?',
    'details.cancelMatch': 'Cancel Match',
    'details.cancelMatchConfirm': 'Do you want to cancel this match?',
    'details.withdrawMatch': 'Cancel participation',
    'details.withdrawMatchConfirm': 'Cancel your participation? The request will become pending again.',
    'details.cancelReason': 'Cancellation reason:',
    'details.cancelReasonPlaceholder': 'Write the reason here...',
    'details.cancelReasonRequired': 'Please provide a reason to cancel.',
    'details.cancelled': 'Cancelled',
    'details.expired': 'Request expired',
    'details.matchFull': 'Match full',
    'details.matchFullError': 'Match is already full',
    'details.matchFullInfo': 'This request is no longer available. The match is already full.',
    'details.notFound': 'Request not found',
    
    // Tabs
    'tabs.home': 'Home',
    'tabs.notifications': 'Notifications',
    'tabs.create': 'Create',
    'tabs.messages': 'Messages',
    'tabs.profile': 'Profile',

    // Messages
    'messages.title': 'Messages',
    'messages.chatTitle': 'Chat',
    'messages.subtitle': 'Short messages with friends to plan matches — not a general chat.',
    'messages.coordinationHint': 'Use this to agree on time and place. Please keep it brief.',
    'messages.placeholder': 'Write a message…',
    'messages.send': 'Send',
    'messages.openChat': 'Message',
    'messages.youPrefix': 'You:',
    'messages.emptyTitle': 'No conversations yet',
    'messages.emptyBody': 'Open a friend’s profile or use the chat icon in your friends list.',
    'messages.friendsOnly': 'You can only message people on your friends list.',
    'messages.listLoadError': 'Could not load conversations. Check your connection and try again.',
    'messages.comingSoon': 'Coming soon',

    // Menu
    'menu.title': 'Menu',
    'menu.profile': 'Profile',
    'menu.friends': 'Friends',
    'menu.matchHistory': 'Match History',
    'menu.share': 'Share App',
    'menu.language': 'Language',
    'menu.options': 'Options',
    'menu.account': 'Account',
    'menu.about': 'About',
    'menu.notifications': 'Notifications',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.empty': 'No notifications yet',
    'notifications.emptySubtext': 'You will see friend requests, matches and more here',
    'notifications.settings': 'Notification settings',
    'notifications.friendRequest': 'Friend requests',
    'notifications.matchConfirmed': 'Match confirmed',
    'notifications.matchRequest': 'Match request from friend',
    'notifications.matchDeclined': 'Match declined',
    'notifications.matchWithdrawn': 'Participant withdrew',
    'notifications.matchCancelled': 'Match cancelled',
    'notifications.matchExpired': 'Request expired',
    'notifications.friendAccepted': 'Friend accepted your request',
    'notifications.type.friendRequest': 'Friend request',
    'notifications.type.matchConfirmed': 'Match confirmed',
    'notifications.type.matchRequest': 'Match request',
    'notifications.type.matchDeclined': 'Match declined',
    'notifications.type.matchWithdrawn': 'Participant withdrew',
    'notifications.type.matchCancelled': 'Match cancelled',
    'notifications.type.matchExpired': 'Request expired',
    'notifications.type.friendAccepted': 'Friend accepted',
    'notifications.justNow': 'Just now',
    'notifications.minAgo': '{n} min ago',
    'notifications.hoursAgo': '{n} hrs ago',
    'notifications.daysAgo': '{n} days ago',
    'notifications.body.friendRequest': '{name} wants to add you as a friend',
    'notifications.body.matchRequest': '{sport} on {date}',
    'notifications.body.matchConfirmed': '{sport} match confirmed',
    'notifications.body.matchExpired': '{sport} on {date}',
    'notifications.body.matchWithdrawn': '{sport} on {date}',
    'notifications.body.friendAccepted': '{name} accepted your friend request',

    // Match History
    'matchHistory.title': 'Match History',
    'matchHistory.titleForFriend': 'Match History ({name})',
    'matchHistory.noMatches': 'No matches yet',
    
    // Share
    'share.title': 'Find A Match',
    'share.message': 'Check out Find A Match - an app to find tennis partners and schedule matches! Download it now!',
    'share.error': 'Unable to share the app',
    
    // Settings
    'settings.title': 'Options',
    'settings.darkMode': 'Dark mode',
    'settings.languages': 'Languages',
    'settings.selectLanguages': 'Select Languages',
    'settings.appLanguage': 'App Language',
    'settings.language.german': 'German',
    'settings.language.english': 'English',
    'settings.account': 'Account',
    'settings.accountSubtitle': 'Update your email and password',
    'settings.email': 'Email',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.updateEmail': 'Update Email',
    'settings.emailUpdated': 'Email updated',
    'settings.emailError': 'Unable to update email',
    'settings.passwordRequired': 'Please enter your current password',
    'settings.newPasswordRequired': 'Please enter a new password',
    'settings.updatePassword': 'Update Password',
    'settings.passwordUpdated': 'Password updated',
    'settings.passwordError': 'Unable to update password',
    'settings.resetPassword': 'Send password reset email',
    'settings.resetSent': 'Password reset email sent',
    'settings.resetError': 'Unable to send reset email',
    'settings.deleteAccount': 'Delete account',
    'settings.deleteWarning': 'This will permanently delete your account. This action cannot be undone.',
    'settings.deleteConfirm': 'Delete',
    'settings.deleteError': 'Unable to delete account',
    'settings.notifications': 'Notifications',
    'settings.sectionAppearance': 'Appearance',
    'settings.sectionLanguage': 'Language',
    'settings.sectionNotifications': 'Notifications',
    'settings.sectionPlanning': 'Planning',
    'settings.requestExpiryTitle': 'When unmatched requests expire',
    'settings.requestExpiryHint': 'For requests you create that do not have enough acceptances yet.',
    'settings.requestExpiry.start': 'At start of time slot',
    'settings.requestExpiry.end': 'At end of time slot',
    
    // Friends
    'friends.title': 'Friends',
    'friends.addFriend': 'Add Friend',
    'friends.addByUsername': 'Add Friend by Username',
    'friends.enterUsername': 'Enter username',
    'friends.sendRequest': 'Send Request',
    'friends.or': 'OR',
    'friends.inviteViaShare': 'Invite via WhatsApp/Email',
    'friends.requests': 'Friend Requests',
    'friends.wantsToAdd': 'wants to add you as a friend',
    'friends.accept': 'Accept',
    'friends.decline': 'Decline',
    'friends.delete': 'Delete',
    'friends.deleteRequest': 'Delete request',
    'friends.deleteRequestConfirm': 'Do you want to remove this friend request?',
    'friends.myFriends': 'My Friends',
    'friends.noFriends': 'No friends yet',
    'friends.addFirstFriend': 'Add your first friend to get started!',
    'friends.pending': 'Pending',
    'friends.inviteTitle': 'Join me on Find A Match!',
    'friends.inviteMessage': 'Hey! Join me on Find A Match - an app to find tennis partners! Add me with my username: {username}',
    'friends.success': 'Success',
    'friends.error': 'Error',
    'friends.inviteSent': 'Invite sent successfully!',
    'friends.inviteError': 'Unable to send invite',
    'friends.emptyUsername': 'Please enter a username',
    'friends.requestSent': 'Friend request sent!',
    'friends.requestAccepted': 'Friend request accepted!',
    'friends.requestError': 'Unable to send friend request',
    'friends.filterBySport': 'Filter by sport',
    'friends.allSports': 'All',
    'friends.searchPlaceholder': 'Search by name or username...',
    'friends.searchMinChars': 'Type at least 2 characters',
    'friends.noResults': 'No users found',
    'friends.add': 'Add',
    'friends.requestSentShort': 'Sent',

    // Friend Profile
    'friendProfile.title': 'Friend Profile',
    'friendProfile.sports': 'Sports',
    'friendProfile.friends': 'Friends',
    'friendProfile.friendsOf': 'Friends of {name}',
    'friendProfile.matches': 'Matches',
    'friendProfile.noSports': 'No sports selected',
    'friendProfile.noFriends': 'No friends to show',
    'friendProfile.loadError': 'Unable to load profile',
    'friendProfile.notFound': 'Friend not found',
    
    // Profile
    'profile.title': 'Profile',
    'profile.photo': 'Profile Photo',
    'profile.username': 'Username',
    'profile.displayName': 'Name',
    'profile.email': 'Email',
    'profile.save': 'Save',
    'profile.saving': 'Saving...',
    'profile.saved': 'Profile updated',
    'profile.saveError': 'Unable to update profile',
    'profile.changePhoto': 'Change Photo',
    'profile.uploading': 'Uploading...',
    'profile.photoUpdated': 'Profile photo updated',
    'profile.uploadError': 'Unable to upload photo',
    'profile.permissionError': 'Permission to access photos is required',
    'profile.currentPassword': 'Current Password',
    'profile.updateEmail': 'Update Email',
    'profile.emailUpdated': 'Email updated',
    'profile.emailError': 'Unable to update email',
    'profile.passwordRequired': 'Please enter your current password',
    'profile.logout': 'Log out',
    'profile.namePlaceholder': 'Your name',
    'profile.bioPlaceholder': 'Write a short bio',
    'profile.sportsTitle': 'Sports',

    // Auth
    'auth.loginTitle': 'Sign In',
    'auth.signupTitle': 'Create Account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.username': 'Username',
    'auth.login': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.noAccount': "Don't have an account? Sign up",
    'auth.forgotPassword': 'Forgot password?',
    'auth.resetPasswordSent': 'Password reset email sent. Check your inbox.',
    'auth.resetPasswordPrompt': 'Please enter your email address above first.',
    'auth.haveAccount': 'Already have an account? Sign in',
    'auth.errorRequired': 'Please fill in all fields',
    'auth.errorPassword': 'Password must be at least 6 characters',
    'auth.errorGeneric': 'Something went wrong',
    'auth.or': 'or',
    'auth.googleSignIn': 'Continue with Google',
    'auth.googleSignUp': 'Sign up with Google',
    'settings.googleOnlyHint':
      'You signed in with Google. Email and password for this app are managed in your Google account.',
    'settings.passwordSectionTitle': 'Email & password',
    'settings.googleDeleteLabel': 'Delete account (confirm with Google)',
    'settings.googleNotConfigured': 'Google sign-in: add your Web Client ID in app.json → expo.extra.googleWebClientId',
    'settings.sectionAccountAuth': 'Account & sign-in',
    'settings.googleAccountSetupNote':
      'Google login needs the Web Client ID in app.json (expo.extra.googleWebClientId) and Google enabled under Firebase → Authentication.',

    // Common
    'common.ok': 'OK',
    'common.cancel': 'Cancel',
  },
  de: {
    // Home Screen
    'app.title': 'Find A Match',
    'app.subtitle': 'Finde dein nächstes Match!',
    'app.pendingRequests': 'Ausstehende Anfragen',
    'app.myRequests': 'Meine Anfragen',
    'app.myPendingRequests': 'Meine ausstehenden Anfragen',
    'app.incomingRequests': 'Anfragen von Freunden',
    'app.confirmedMatches': 'Bestätigte Matches',
    'app.cancelledRequests': 'Stornierte Anfragen',
    'app.noRequests': 'Noch keine Anfragen',
    'app.noRequestsSubtext': 'Tippe auf die + Schaltfläche, um eine zu erstellen!',
    'app.cancelled': 'Storniert',
    'app.acceptedCount': '{count}/{total} akzeptiert',
    'app.accepted': 'Akzeptiert',
    'app.declined': 'Abgelehnt',
    'app.declinedBy': 'Abgelehnt von',
    'app.allDeclined': 'Alle haben abgelehnt',
    'app.actionRequired': 'Aktion erforderlich',
    'app.waitingForFriends': 'Warte auf Freunde',
    'app.incomingResponded': 'Du hast bereits geantwortet',
    'app.creator': 'Ersteller',
    'app.with': 'Mit',
    'app.friendsInvitedOne': '1 Freund eingeladen',
    'app.friendsInvitedCount': '{count} Freunde eingeladen',
    'home.newFriendRequestOne': '1 neue Freundesanfrage',
    'home.newFriendRequestCount': '{count} neue Freundesanfragen',
    
    // Request Screen
    'request.title': 'Neue Anfrage',
    'request.date': 'Datum',
    'request.timeSection': 'Zeit',
    'request.timeRangeMode': 'Zeitraum',
    'request.exactTimeMode': 'Genaue Zeit',
    'request.timeRangeHint': 'Freund kann innerhalb des Zeitraums wählen',
    'request.exactTimeHint': 'Match ist zu dieser genauen Zeit',
    'request.startTime': 'Start',
    'request.endTime': 'Ende',
    'request.selectSport': 'Sportart auswählen',
    'request.selectFriends': 'Freunde auswählen',
    'request.selected': 'ausgewählt',
    'request.noFriends': 'Noch keine Freunde',
    'request.noFriendsSubtext': 'Füge Freunde zu deiner Liste hinzu, um Tennis-Anfragen zu senden',
    'request.noFriendsForSport': 'Keine Freunde mit dieser Sportart',
    'request.send': 'Anfrage senden',
    'request.errorNoFriends': 'Bitte wähle mindestens einen Freund aus',
    'request.errorNoSport': 'Bitte wähle eine Sportart aus',
    'request.errorTime': 'Endzeit muss nach der Startzeit liegen',
    'request.players': 'Spieleranzahl',
    'request.inviteAll': 'Alle einladen',
    'request.inviteAllWithCount': 'Alle einladen ({count})',
    'request.inviteSome': 'Freunde auswählen',
    'request.inviteSomeWithCount': 'Freunde auswählen ({count})',
    'request.errorPlayers': 'Bitte gültige Spieleranzahl eingeben',
    'request.errorPlayersTooMany': 'Nicht genug Freunde für diese Spieleranzahl',
    'request.locationOptional': 'Ort (optional)',
    'request.locationPlaceholder': 'z. B. Tennis-Club, Park XYZ',
    'request.comment': 'Kommentar (für alle sichtbar)',
    'request.commentPlaceholder': 'z. B. Bälle mitbringen, Platz 3 reserviert...',
    'request.durationOptional': 'Dauer (optional, Minuten)',
    'request.durationRequired': 'Spieldauer (Minuten)',
    'request.durationPlaceholder': 'z. B. 120',
    'request.durationCalculated': 'Spieldauer',
    'request.errorDuration': 'Bitte gültige Dauer eingeben',
    'request.errorDurationRequired': 'Bitte gib die Spieldauer für den Zeitraum an',
    'request.update': 'Anfrage aktualisieren',
    'request.success': 'Erfolg',
    'request.sent': 'Anfrage an {count} Freund(e) gesendet!',
    
    // Request Details
    'details.title': 'Match',
    'details.titleWithSport': '{sport} Match',
    'details.headerTitle': 'Anfrage-Details',
    'details.confirmed': '✓ Bestätigt',
    'details.date': 'Datum:',
    'details.time': 'Zeit:',
    'details.timeRange': 'Zeitraum:',
    'details.sport': 'Sport:',
    'details.location': 'Ort:',
    'details.comment': 'Kommentar:',
    'details.friendsInvited': 'Eingeladene Freunde:',
    'details.participants': 'Teilnehmer',
    'details.you': '(Du)',
    'details.organizer': 'Organisator',
    'details.accepted': '✓ Akzeptiert:',
    'details.acceptTime': 'Match bestätigen',
    'details.startTime': 'Start',
    'details.endTime': 'Ende',
    'details.waiting': 'Warte auf Antwort...',
    'details.proposed': 'Vorschlag:',
    'details.accept': 'Akzeptieren',
    'details.decline': 'Ablehnen',
    'details.declineMatch': 'Match ablehnen',
    'details.declineMatchConfirm': 'Möchtest du dieses Match wirklich ablehnen? Diese Aktion kann nicht rückgängig gemacht werden.',
    'details.declined': 'Abgelehnt',
    'details.withdrawn': 'Abgesagt',
    'details.durationOutOfRange': 'Ausgewählte Zeit passt nicht zur Dauer',
    'details.duration': 'Dauer:',
    'details.suggestedTimes': 'Zeitvorschläge',
    'details.deleteRequest': 'Anfrage löschen',
    'details.deleteConfirm': 'Möchtest du diese Anfrage löschen?',
    'details.editRequest': 'Anfrage bearbeiten',
    'details.editRequestPrompt': 'Möchtest du diese Anfrage bearbeiten?',
    'details.acceptedBy': 'Akzeptiert von',
    'details.declinedBy': 'Abgelehnt von',
    'details.hasDeclines': 'Nicht bestätigbar, solange jemand abgelehnt hat',
    'details.confirmMatch': 'Match bestätigen',
    'details.errorNoAcceptances': 'Noch kein Freund hat eine Zeit akzeptiert',
    'details.matchConfirmed': 'Match bestätigt!',
    'details.onlyCreatorConfirm': 'Nur der Ersteller kann das Match bestätigen.',
    'details.completed': 'Gespielt',
    'details.completeMatch': 'Als gespielt markieren',
    'details.completeMatchConfirm': 'Dieses Match als gespielt markieren?',
    'details.matchCompleted': 'Match als gespielt markiert!',
    'details.cancelRequest': 'Anfrage stornieren',
    'details.cancelConfirm': 'Möchtest du diese Anfrage stornieren?',
    'details.cancelMatch': 'Match absagen',
    'details.cancelMatchConfirm': 'Möchtest du dieses Match absagen?',
    'details.withdrawMatch': 'Teilnahme absagen',
    'details.withdrawMatchConfirm': 'Deine Teilnahme absagen? Die Anfrage wird wieder offen.',
    'details.cancelReason': 'Begründung:',
    'details.cancelReasonPlaceholder': 'Begründung hier eingeben...',
    'details.cancelReasonRequired': 'Bitte gib eine Begründung an.',
    'details.cancelled': 'Storniert',
    'details.expired': 'Anfrage abgelaufen',
    'details.matchFull': 'Match voll',
    'details.matchFullError': 'Das Match ist bereits voll',
    'details.matchFullInfo': 'Diese Anfrage ist nicht mehr verfügbar. Das Match ist bereits voll.',
    'details.notFound': 'Anfrage nicht gefunden',
    
    // Tabs
    'tabs.home': 'Home',
    'tabs.notifications': 'Benachrichtigungen',
    'tabs.create': 'Erstellen',
    'tabs.messages': 'Nachrichten',
    'tabs.profile': 'Profil',

    // Messages
    'messages.title': 'Nachrichten',
    'messages.chatTitle': 'Chat',
    'messages.subtitle': 'Kurze Nachrichten mit Freunden zum Verabreden — kein allgemeiner Chat.',
    'messages.coordinationHint': 'Hier könnt ihr Zeit und Ort abstimmen. Bitte kurz halten.',
    'messages.placeholder': 'Nachricht schreiben…',
    'messages.send': 'Senden',
    'messages.openChat': 'Nachricht',
    'messages.youPrefix': 'Du:',
    'messages.emptyTitle': 'Noch keine Unterhaltungen',
    'messages.emptyBody': 'Öffne das Profil eines Freundes oder tippe auf das Chat-Symbol in der Freundesliste.',
    'messages.friendsOnly': 'Du kannst nur Personen schreiben, die in deiner Freundesliste stehen.',
    'messages.listLoadError': 'Unterhaltungen konnten nicht geladen werden. Verbindung prüfen und erneut versuchen.',
    'messages.comingSoon': 'Demnächst verfügbar',

    // Menu
    'menu.title': 'Menü',
    'menu.profile': 'Profil',
    'menu.friends': 'Freunde',
    'menu.matchHistory': 'Match-Verlauf',
    'menu.share': 'App teilen',
    'menu.language': 'Sprache',
    'menu.options': 'Optionen',
    'menu.account': 'Konto',
    'menu.about': 'Über',
    'menu.notifications': 'Benachrichtigungen',

    // Notifications
    'notifications.title': 'Benachrichtigungen',
    'notifications.empty': 'Noch keine Benachrichtigungen',
    'notifications.emptySubtext': 'Freundesanfragen, Matches und mehr erscheinen hier',
    'notifications.settings': 'Benachrichtigungseinstellungen',
    'notifications.friendRequest': 'Freundesanfragen',
    'notifications.matchConfirmed': 'Match bestätigt',
    'notifications.matchRequest': 'Match-Anfrage von Freund',
    'notifications.matchDeclined': 'Match abgelehnt',
    'notifications.matchWithdrawn': 'Teilnehmer hat abgesagt',
    'notifications.matchCancelled': 'Match abgesagt',
    'notifications.matchExpired': 'Anfrage abgelaufen',
    'notifications.friendAccepted': 'Freund hat Anfrage angenommen',
    'notifications.type.friendRequest': 'Freundesanfrage',
    'notifications.type.matchConfirmed': 'Match bestätigt',
    'notifications.type.matchRequest': 'Match-Anfrage',
    'notifications.type.matchDeclined': 'Match abgelehnt',
    'notifications.type.matchWithdrawn': 'Teilnehmer hat abgesagt',
    'notifications.type.matchCancelled': 'Match abgesagt',
    'notifications.type.matchExpired': 'Anfrage abgelaufen',
    'notifications.type.friendAccepted': 'Freund hat angenommen',
    'notifications.justNow': 'Gerade eben',
    'notifications.minAgo': 'Vor {n} Min.',
    'notifications.hoursAgo': 'Vor {n} Std.',
    'notifications.daysAgo': 'Vor {n} Tagen',
    'notifications.body.friendRequest': '{name} möchte dich als Freund hinzufügen',
    'notifications.body.matchRequest': '{sport} am {date}',
    'notifications.body.matchConfirmed': '{sport} Match bestätigt',
    'notifications.body.matchExpired': '{sport} am {date}',
    'notifications.body.matchWithdrawn': '{sport} am {date}',
    'notifications.body.friendAccepted': '{name} hat deine Freundesanfrage angenommen',

    // Match History
    'matchHistory.title': 'Match-Verlauf',
    'matchHistory.titleForFriend': 'Match-Verlauf ({name})',
    'matchHistory.noMatches': 'Noch keine Matches',
    
    // Share
    'share.title': 'Find A Match',
    'share.message': 'Schau dir Find A Match an - eine App, um Tennispartner zu finden und Matches zu planen! Jetzt herunterladen!',
    'share.error': 'App konnte nicht geteilt werden',
    
    // Settings
    'settings.title': 'Optionen',
    'settings.darkMode': 'Dunkelmodus',
    'settings.languages': 'Sprachen',
    'settings.selectLanguages': 'Sprachen auswählen',
    'settings.appLanguage': 'App-Sprache',
    'settings.language.german': 'Deutsch',
    'settings.language.english': 'Englisch',
    'settings.account': 'Konto',
    'settings.accountSubtitle': 'E-Mail und Passwort aktualisieren',
    'settings.email': 'E-Mail',
    'settings.currentPassword': 'Aktuelles Passwort',
    'settings.newPassword': 'Neues Passwort',
    'settings.updateEmail': 'E-Mail aktualisieren',
    'settings.emailUpdated': 'E-Mail aktualisiert',
    'settings.emailError': 'E-Mail konnte nicht aktualisiert werden',
    'settings.passwordRequired': 'Bitte aktuelles Passwort eingeben',
    'settings.newPasswordRequired': 'Bitte neues Passwort eingeben',
    'settings.updatePassword': 'Passwort aktualisieren',
    'settings.passwordUpdated': 'Passwort aktualisiert',
    'settings.passwordError': 'Passwort konnte nicht aktualisiert werden',
    'settings.resetPassword': 'Passwort-Reset E-Mail senden',
    'settings.resetSent': 'Passwort-Reset E-Mail gesendet',
    'settings.resetError': 'Reset E-Mail konnte nicht gesendet werden',
    'settings.deleteAccount': 'Konto löschen',
    'settings.deleteWarning': 'Dies löscht dein Konto dauerhaft. Diese Aktion kann nicht rückgängig gemacht werden.',
    'settings.deleteConfirm': 'Löschen',
    'settings.deleteError': 'Konto konnte nicht gelöscht werden',
    'settings.notifications': 'Benachrichtigungen',
    'settings.sectionAppearance': 'Darstellung',
    'settings.sectionLanguage': 'Sprache',
    'settings.sectionNotifications': 'Benachrichtigungen',
    'settings.sectionPlanning': 'Planung',
    'settings.requestExpiryTitle': 'Wann offene Anfragen ablaufen',
    'settings.requestExpiryHint': 'Gilt für deine eigenen Anfragen, solange noch nicht genug Zusagen da sind.',
    'settings.requestExpiry.start': 'Wenn die Startzeit erreicht ist',
    'settings.requestExpiry.end': 'Wenn die Endzeit des Zeitfensters erreicht ist',
    
    // Friends
    'friends.title': 'Freunde',
    'friends.addFriend': 'Freund hinzufügen',
    'friends.addByUsername': 'Freund per Benutzername hinzufügen',
    'friends.enterUsername': 'Benutzername eingeben',
    'friends.sendRequest': 'Anfrage senden',
    'friends.or': 'ODER',
    'friends.inviteViaShare': 'Via WhatsApp/E-Mail einladen',
    'friends.requests': 'Freundesanfragen',
    'friends.wantsToAdd': 'möchte dich als Freund hinzufügen',
    'friends.accept': 'Akzeptieren',
    'friends.decline': 'Ablehnen',
    'friends.delete': 'Löschen',
    'friends.deleteRequest': 'Anfrage löschen',
    'friends.deleteRequestConfirm': 'Möchtest du diese Freundesanfrage entfernen?',
    'friends.myFriends': 'Meine Freunde',
    'friends.noFriends': 'Noch keine Freunde',
    'friends.addFirstFriend': 'Füge deinen ersten Freund hinzu, um loszulegen!',
    'friends.pending': 'Ausstehend',
    'friends.inviteTitle': 'Tritt mir bei Find A Match bei!',
    'friends.inviteMessage': 'Hey! Tritt mir bei Find A Match bei - einer App, um Tennispartner zu finden! Füge mich mit meinem Benutzernamen hinzu: {username}',
    'friends.success': 'Erfolg',
    'friends.error': 'Fehler',
    'friends.inviteSent': 'Einladung erfolgreich gesendet!',
    'friends.inviteError': 'Einladung konnte nicht gesendet werden',
    'friends.emptyUsername': 'Bitte gib einen Benutzernamen ein',
    'friends.requestSent': 'Freundesanfrage gesendet!',
    'friends.requestAccepted': 'Freundesanfrage akzeptiert!',
    'friends.requestError': 'Freundesanfrage konnte nicht gesendet werden',
    'friends.filterBySport': 'Nach Sportart filtern',
    'friends.allSports': 'Alle',
    'friends.searchPlaceholder': 'Nach Name oder Benutzername suchen...',
    'friends.searchMinChars': 'Mindestens 2 Zeichen eingeben',
    'friends.noResults': 'Keine Nutzer gefunden',
    'friends.add': 'Hinzufügen',
    'friends.requestSentShort': 'Gesendet',

    // Friend Profile
    'friendProfile.title': 'Freundesprofil',
    'friendProfile.sports': 'Sportarten',
    'friendProfile.friends': 'Freunde',
    'friendProfile.friendsOf': 'Freunde von {name}',
    'friendProfile.matches': 'Matches',
    'friendProfile.noSports': 'Keine Sportarten ausgewählt',
    'friendProfile.noFriends': 'Keine Freunde vorhanden',
    'friendProfile.loadError': 'Profil konnte nicht geladen werden',
    'friendProfile.notFound': 'Freund nicht gefunden',
    
    // Profile
    'profile.title': 'Profil',
    'profile.photo': 'Profilbild',
    'profile.username': 'Benutzername',
    'profile.displayName': 'Name',
    'profile.email': 'E-Mail',
    'profile.save': 'Speichern',
    'profile.saving': 'Speichern...',
    'profile.saved': 'Profil aktualisiert',
    'profile.saveError': 'Profil konnte nicht aktualisiert werden',
    'profile.changePhoto': 'Foto ändern',
    'profile.uploading': 'Hochladen...',
    'profile.photoUpdated': 'Profilbild aktualisiert',
    'profile.uploadError': 'Profilbild konnte nicht hochgeladen werden',
    'profile.permissionError': 'Zugriff auf Fotos erforderlich',
    'profile.currentPassword': 'Aktuelles Passwort',
    'profile.updateEmail': 'E-Mail aktualisieren',
    'profile.emailUpdated': 'E-Mail aktualisiert',
    'profile.emailError': 'E-Mail konnte nicht aktualisiert werden',
    'profile.passwordRequired': 'Bitte aktuelles Passwort eingeben',
    'profile.logout': 'Abmelden',
    'profile.namePlaceholder': 'Dein Name',
    'profile.bioPlaceholder': 'Kurze Bio schreiben',
    'profile.sportsTitle': 'Sportarten',

    // Auth
    'auth.loginTitle': 'Anmelden',
    'auth.signupTitle': 'Konto erstellen',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.username': 'Benutzername',
    'auth.login': 'Anmelden',
    'auth.signup': 'Registrieren',
    'auth.noAccount': 'Noch kein Konto? Registrieren',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.resetPasswordSent': 'E-Mail zum Zurücksetzen gesendet. Prüfe deinen Posteingang.',
    'auth.resetPasswordPrompt': 'Bitte zuerst deine E-Mail-Adresse oben eingeben.',
    'auth.haveAccount': 'Schon ein Konto? Anmelden',
    'auth.errorRequired': 'Bitte alle Felder ausfüllen',
    'auth.errorPassword': 'Passwort muss mindestens 6 Zeichen haben',
    'auth.errorGeneric': 'Etwas ist schiefgelaufen',
    'auth.or': 'oder',
    'auth.googleSignIn': 'Mit Google anmelden',
    'auth.googleSignUp': 'Mit Google registrieren',
    'settings.googleOnlyHint':
      'Du bist mit Google angemeldet. E-Mail und Passwort für diese App werden über dein Google-Konto geregelt.',
    'settings.passwordSectionTitle': 'E-Mail & Passwort',
    'settings.googleDeleteLabel': 'Konto löschen (mit Google bestätigen)',
    'settings.googleNotConfigured': 'Google-Anmeldung: Web-Client-ID in app.json unter expo.extra.googleWebClientId eintragen',
    'settings.sectionAccountAuth': 'Konto & Anmeldung',
    'settings.googleAccountSetupNote':
      'Für Google-Login: Web-Client-ID in app.json (expo.extra.googleWebClientId) eintragen und Google unter Firebase → Authentication aktivieren.',

    // Common
    'common.ok': 'OK',
    'common.cancel': 'Abbrechen',
  },
};

export const LanguageProvider = ({ children }) => {
  const [selectedLanguages, setSelectedLanguages] = useState(['en']); // Default to English
  const [primaryLanguage, setPrimaryLanguage] = useState('en');

  // Load saved languages on mount
  React.useEffect(() => {
    loadLanguages();
  }, []);

  const loadLanguages = async () => {
    try {
      const saved = await AsyncStorage.getItem('selectedLanguages');
      const primary = await AsyncStorage.getItem('primaryLanguage');
      if (saved) {
        const languages = JSON.parse(saved);
        setSelectedLanguages(languages);
      }
      if (primary) {
        setPrimaryLanguage(primary);
      }
    } catch (error) {
      console.error('Error loading languages:', error);
    }
  };

  const saveLanguages = async (languages, primary) => {
    try {
      await AsyncStorage.setItem('selectedLanguages', JSON.stringify(languages));
      await AsyncStorage.setItem('primaryLanguage', primary);
      setSelectedLanguages(languages);
      setPrimaryLanguage(primary);
    } catch (error) {
      console.error('Error saving languages:', error);
    }
  };

  const t = (key, params = {}) => {
    let text = translations[primaryLanguage]?.[key] || translations['en'][key] || key;
    
    // Replace parameters
    Object.keys(params).forEach(param => {
      text = text.replace(`{${param}}`, params[param]);
    });
    
    return text;
  };

  return (
    <LanguageContext.Provider
      value={{
        selectedLanguages,
        primaryLanguage,
        setLanguages: saveLanguages,
        t,
        availableLanguages: [
          { code: 'en', name: 'English', nativeName: 'English' },
          { code: 'de', name: 'German', nativeName: 'Deutsch' },
        ],
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};
